module.exports = {
  parser: 'typescript',
  arrowParens: 'always',
  bracketSpacing: false,
  htmlWhitespaceSensitivity: 'css',
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 110,
  proseWrap: 'never',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'none',
  useTabs: false,
};
